### ISSUE TITLE
API for opening

### ISSUE THREAD

**Issue by xXNiceYT** [Blugin/InventoryMonitor-PMMP#15]
How do I open chest without UI showing

For example:

/im <player>

If you type /im xxnicehq
It open chest not a ui to confirm

**Comment by xXNiceYT** [comment]
here my try
					if($syncInventory instanceof SyncInventory){
						ConfirmForm::$instances[$sender->getLowerCaseName()] = $this;
					$syncInventory->sendFakeChestBlock($sender);
					$sender->addWindow($syncInventory);
					unset(ConfirmForm::$instances[$sender->getLowerCaseName()]);
				}

**Comment by FreeGamingHere** [comment]
> $pk = new BlockEventPacket();
$pk->x = $block->x;
$pk->y = $block->y;
$pk->z = $block->z;
$pk->eventType = 1;
$pk->eventData = 1;

**Comment by FreeGamingHere** [comment]
To open a chest. I do not know how this thing works.

**Comment by xXNiceYT** [comment]
Lol
